import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SHOFEUR',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="description" content="Shofeur is your go-to resource for booking luxury vehicle experiences for your special occasions!" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
